### ISSUE TITLE
The script is not working with me 

### ISSUE THREAD

**Issue by abdelkareemkobo** [rachsmithcodes/obsidian-to-astro-sync#3]
I have a images directory in the obsidian vault  and configured the config.js with right paths
but get the following error 
```js 
[Error :ENONT: no such file or directory, open '/home/kareem/obsidian_valuts/logseq/religion/cool.md']{
errno:-2,
code: "ENOENT",
syscall: "open",
Path: "my_path",}
```

**Comment by abdelkareemkobo** [comment]
This is what i get after run `sudo npm run start`
![image](https://github.com/rachsmithcodes/obsidian-to-astro-sync/assets/72500236/c440b1ff-ff98-4fc9-9251-feb1651efd72)

**Comment by rachsmithcodes** [comment]
hi,

your path looks like it has `obsidian_valuts` in it, is it meant to be `obsidian_vaults`?

**Comment by abdelkareemkobo** [comment]
@rachsmithcodes yes!
